arkAS/Controllers/DemoController.cs
using arkAS.BLL;
using arkAS.BLL.Core;
using arkAS.BLL.CRM;
using arkAS.Models;
using ClosedXML.Excel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Data.SqlClient;
using System.Configuration;
using Dapper;
using System.Data;
using System.Web.Script.Serialization;
using arkAS.BLL.Calc;
using Newtonsoft.Json;
using System.Net;
using Glimpse.Core.Extensions;
using arkAS.BLL.Calendar;

namespace arkAS.Controllers
{
    public class DemoController : Controller
    {
        static string PathChapter = @"/uploads/Images/users_avatar/";
        static string FileStandart = @"avatar.png";
        static string GuiDefault = @"83e9d28d-e644-460e-9fc6-44999afb80c2";//hecrus@mail.ru
        public DemoController()
        {
            string PathCurrent = AppDomain.CurrentDomain.BaseDirectory + PathChapter;
            if (!Directory.Exists(PathCurrent))
            {
                Directory.CreateDirectory(PathCurrent);
            }
        }

        public ActionResult Kanban()
        {
            var mng = new SettingsManager();
            SettingsCategoriesViewMdels model = new SettingsCategoriesViewMdels();
            model.settingCategories  = mng.db.GetSettingCategories();            
            model.settings = new List<as_settings>();
            foreach(var item in model.settingCategories)
            {
                foreach(var it in item.as_settings)
                {
                    model.settings.Add(it);
                }
            }
            return View(model);
        }

        public ActionResult SaveSetting(string code, string value,
            int category, string value2, string name)
        {
            var mng = new SettingsManager();

            as_settings setting = new as_settings
            {
                code = code,
                value=value,
                categoryID=category,
                value2=value2,
                name=name
            };

            var result = mng.SaveSetting(setting);

            return Json(new
            {
                result
            });
        }

        public ActionResult EditSetting(int id, string fieldValue, string fieldName)
        {
            var mng = new SettingsManager();
            bool result = mng.EditSettingField(id, fieldName, fieldValue);
            return Json(new
            {
                result
            });
        }

        public ActionResult Categories()
        {
            var mng = new CategoryManager();
            ViewBag.Categories = mng.GetCategories();
            return View();

        }

        public ActionResult Statuses()
        {
            var mng = new StatusesManager();
            ViewBag.Statuses = mng.db.GetStatuses();
            return View();

        }



        public ActionResult SettingCategories()
        {
            var mng = new SettingsManager();
            ViewBag.SettingCategories = mng.db.GetSettingCategories();
            return View();

        }
        // LESS
        public ActionResult Less()
        {
            return View();
        }

        //Socials Network
        public ActionResult SocialNetworks()
        {
            return View();
        }

        //Post via vk api
        public ActionResult VkPost()
        {
            return View();
        }

        public ActionResult SqlCrud()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return Redirect("/Account/Login/?demoType=SqlCrud");

            }

        }

        

        public ActionResult GetSqlCommand()
        {
            var parameters = AjaxModel.GetAjaxParameters(HttpContext);
            var code = parameters["code"].ToStringOrDefault();
            var pageSize = RDL.Convert.StrToInt(parameters["pageSize"].ToString(), 1);
            var page = RDL.Convert.StrToInt(parameters["page"].ToString(), 1);
            var mng = new SqlCrudManager();
            var sqlID = mng.GetSqlCruds().Where(x => x.code == code).Select(x => x.id).FirstOrDefault();
            var rol = mng.GetSqlCruds().Where(x => x.as_sqlRole.Any(y => y.sqlID==sqlID)).ToList();
            if (rol.Count == 0)
            {
                return Json(new
                {
                    S="sql"
                }
            );
            }
            var ww = rol[0].as_sqlRole.Select(x=>x.role);
            
            var edr = Roles.GetRolesForUser(Membership.GetUser().UserName);
            var fd = ww.Intersect(edr).ToList();
            if (fd.Count!=0)
            {
                var command = mng.GetSqlCruds().Where(x => x.code == code).Select(x => x.sql).FirstOrDefault();


               
                var dt = mng.GetSqlCrud(command, null);
                var res = dt.AsEnumerable().Skip(pageSize*(page - 1)).Take(pageSize).ToList();
                return Json(new
                {

                    Table = new
                    {
                        columns = dt.Columns.Cast<DataColumn>().Select(x => x.ColumnName),
                        rows = res.Select(x => new { fields = x.ItemArray }),
                        rowCount = dt.Rows.Count,
                        fullRows=dt.Rows.Cast<DataRow>().Select(x=>x.ItemArray)
                    }
                });
            }
            else
            {
                return Json(new{});
            }


        }

        public ActionResult Googlemap(){
            return View();
        }

        public ActionResult ExampleLess()
        {
            return View();
        }

        // GET: Demo
        public ActionResult Index()
        {
            return View();
        }

        // ----------------------- Simple Table --------------------------
        public ActionResult SimpleTable()
        {
            return View();
        }

        public ActionResult SimpleTable_getItems()
        {
            var parameters = AjaxModel.GetParameters(HttpContext);

            string[] sorts = parameters.sort.Split(",".ToArray(), StringSplitOptions.RemoveEmptyEntries);
            string sort1 = sorts.Length > 0 ? sorts[0] : "";
            string[] directions = parameters.direction.Split(",".ToArray(), StringSplitOptions.RemoveEmptyEntries);
            string direction1 = directions.Length > 0 ? directions[0] : "";

            var rep = new CoreRepository();
            var p = new DynamicParameters();
            p.Add("SortField", sort1);
            p.Add("Directions", direction1);
            p.Add("page", parameters.page);
            p.Add("pageSize", parameters.pageSize);
            p.Add("total", dbType: DbType.Int32, direction: ParameterDirection.Output);

            var items = rep.GetSQLData<dynamic>("[GetSimpleTableDemoTable]", p, CommandType.StoredProcedure);
            var total = p.Get<int>("total");

            var json = JsonConvert.SerializeObject(new
            {
                items,
                total = total
            });
            return Content(json, "application/json");
        }

        public ActionResult SimpleTable_getItemsOldLinq()
        {
            var parameters = AjaxModel.GetParameters(HttpContext);
            var mng = new CRMManager();

            var items = mng.GetOrders().AsQueryable();
            var sorts = parameters.sort.Split(",".ToArray(), StringSplitOptions.RemoveEmptyEntries);
            var directions = parameters.direction.Split(",".ToArray(), StringSplitOptions.RemoveEmptyEntries);
            var sort1 = sorts.Length > 0 ? sorts[0] : "";
            var direction1 = directions.Length > 0 ? directions[0] : "";

            switch (sort1)
            {
                case "orderNum":
                    if (direction1 == "up") items = items.OrderBy(x => x.orderNum);
                    else items = items.OrderByDescending(x => x.orderNum);
                    break;
                case "statusName":
                    if (direction1 == "up") items = items.OrderBy(x => x.crm_orderStatuses.name);
                    else items = items.OrderByDescending(x => x.crm_orderStatuses.name);
                    break;
                case "clientName":
                    if (direction1 == "up") items = items.OrderBy(x => x.crm_clients.fio);
                    else items = items.OrderByDescending(x => x.crm_clients.fio);
                    break;
                default:
                    if (direction1 == "up") items = items.OrderBy(x => x.created);
                    else items = items.OrderByDescending(x => x.created);
                    break;
            }
            var total = items.Count();
            var res = items.Skip(parameters.pageSize * (parameters.page - 1)).Take(parameters.pageSize).ToList();


            return Json(new
            {
                items = res.Select(x => new
                {
                    x.id,
                    x.orderNum,
                    x.statusID,
                    statusName = x.crm_orderStatuses != null ? x.crm_orderStatuses.name : "",
                    x.addedBy,
                    x.clientID,
                    clientName = x.crm_clients != null ? x.crm_clients.fio : "",
                    created = x.created.GetValueOrDefault().ToString("dd.MM.yyyy")
                }),
                total = items.Count()
            }, JsonRequestBehavior.AllowGet);
        }

        // ----------------------- Filter Table --------------------------
        public ActionResult FilterTable()
        {
            var mng = new CRMManager();
            ViewBag.OrderStatuses = mng.GetOrderStatuses();
            ViewBag.Clients = mng.GetClients();
            return View();
        }


        public ActionResult FilterTable_getItems()
        {

arkAS/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace arkAS.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

arkAS/Views/Shared/_Layout.cshtml
@using Glimpse.Mvc.Html
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@(ViewBag.Title ?? "Ark AS")</title>



    @Styles.Render("~/bundles/css")
    @Html.Raw(arkAS.BLL.Core.CoreManager.StyleForDev())
    @RenderSection("css", false)
    @RenderSection("ogp", false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ark AS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Roles.IsUserInRole("admin"))
                    {
                        <li>@Html.ActionLink("Панель управления", "Index", "Admin")</li>
                    }
                    @if (User.Identity.IsAuthenticated && !Roles.IsUserInRole("admin") && !Roles.IsUserInRole("guest"))
                    {
                        <li>@Html.ActionLink("Кабинет", "Index", "Cabinet")</li>
                    }
                    <li>@Html.ActionLink("О нас", "About", "Home")</li>
                    <li>@Html.ActionLink("Как связаться", "Contact", "Home")</li>
                    <li>
                        <a class=" dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Демо <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Все демо", "Index", "Demo")</li>
                            <li><a href="~/Content/sb-admin-2-1.0.5/index.html" target="_blank">Шаблон панели управления</a></li>
                            <li>@Html.ActionLink("Канбан доска", "kanban", "Demo")</li>
                            <li>@Html.ActionLink("Просто вывод таблицы с сортировкой и фильтрами", "SimpleTable", "Demo")</li>
                            <li>@Html.ActionLink("Фильтрация данных", "FilterTable", "Demo")</li>
                            <li>@Html.ActionLink("Inline редактирование", "InlineEditTable", "Demo")</li>
                            <li>@Html.ActionLink("Редактирование через модальную форму", "FullEditTable", "Demo")</li>
                            <li>@Html.ActionLink("Галочки для групповых операций", "GroupOperationTable", "Demo")</li>
                            <li>@Html.ActionLink("Двойная сортировка", "DoubleSortTable", "Demo")</li>
                            <li>@Html.ActionLink("Управляющие кнопки и показ вложенных элементов", "RowButtonsTable", "Demo")</li>
                            <li>@Html.ActionLink("Показ вложенной статистики по дням", "ShowStatTable", "Demo")</li>
                            <li>@Html.ActionLink("Настройка столбцов", "ColSettingsTable", "Demo")</li>
                            <li>@Html.ActionLink("Комментарии к элементам таблицы", "CommentsTable", "Demo")</li>
                            <li>@Html.ActionLink("Копирование другой строки", "CopyRowTable", "Demo")</li>
                            <li>@Html.ActionLink("Экспорт в Excel и PDF", "ExportExcelTable", "Demo")</li>
                            <li>@Html.ActionLink("Инструмент замены в определенных полях", "ReplaceToolTable", "Demo")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("AS Form - создание форм различной сложности", "ASForm", "Demo")</li>
                            <li>@Html.ActionLink("Cоздание простой формы", "SimpleForm", "Demo")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Файловый менеджер", "Example", "FileEditor")</li>
                            <li>@Html.ActionLink("Новости", "GetArticleItems", "Article")</li>
                            <li>@Html.ActionLink("Компонент контроля действий", "AsCtrl", "Demo")</li>
                            <li>@Html.ActionLink("Графики", "Graphic", "Graphic")</li>
                            <li>@Html.ActionLink("AS Info - отображение уточняющего контента для элемента", "PopupInfo", "Demo")</li>
                            <li>@Html.ActionLink("Пример использования Signal R", "SignalR", "Demo")</li>
                            <li>@Html.ActionLink("Пример компонента одиночной замены картинки", "AsImageAsText", "Demo")</li>
                            <li>@Html.ActionLink("Пример элемента профиля пользователя", "ProfileFormUser", "Demo")</li>
                            <li>@Html.ActionLink("Обратный счетчик", "CountDown", "Demo")</li>
                            <li>@Html.ActionLink("Видео на фоне", "VideoBackground", "Demo")</li>
                            <li>@Html.ActionLink("Стандартные ответы на телефонные звонки", "PlayAudio", "Demo")</li>
                            <li>@Html.ActionLink("Горячие кнопки", "HotKeysDemo", "Demo")</li>
                            <li>@Html.ActionLink("Пример использования LESS", "Less", "Demo")</li>
                            <li>@Html.ActionLink("Пример работы с соц.сетями", "SocialNetworks", "Demo")</li>
                            <li>@Html.ActionLink("Пример поста на стену Вконтакте", "VkPost", "Demo")</li>
                            <li>@Html.ActionLink("Сравнение скорости работы шаблонизаторов", "DotJsDemo", "Demo")</li>
                            <li>@Html.ActionLink("Города на карте Google", "Maplaces", "Demo")</li>
                        </ul>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Документооборот (Touch)", "Documents", new { area = "Vasilyev", controller = "Document" })</li>
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="container body-content">
        <div class="body-content2">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Система разработки CRM (личных кабинетов) на заказ Ark AS (Web-automation.ru)</p>
            @Html.Partial("_ViewSwitcher")
        </footer>
    </div>
    <div class="modal fade" id="asModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <p>One fine body&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary">ОК</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script src="~/js/AS/as.resources.js" charset="windows-1251"></script>

    @Scripts.Render("~/bundles/libs")
    @Scripts.Render("~/bundles/as")
    @Scripts.Render("~/bundles/highcharts")
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js?modules=core,widget,mouse,sortable"></script>
    <script src="~/js/AS/controls/as.opinion.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function () { try { w.yaCounter32000186 = new Ya.Metrika({ id: 32000186, clickmap: true, trackLinks: true, accurateTrackBounce: true, webvisor: true }); } catch (e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/32000186" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    @StackExchange.Profiling.MiniProfiler.RenderIncludes()
    @Html.GlimpseClient()
    @RenderSection("js", false)
    <script src="~/signalr/hubs"></script>
</body>
</html>

arkAS/Views/Shared/_LayoutVideo.cshtml
@using Glimpse.Mvc.Html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@(ViewBag.Title ?? "Ark AS")</title>
    
    
    
    @Styles.Render("~/bundles/css")
    @Html.Raw(arkAS.BLL.Core.CoreManager.StyleForDev())
    @RenderSection("css", false)
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ark AS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Roles.IsUserInRole("admin"))
                    {
                        <li>@Html.ActionLink("Панель управления", "Index", "Admin")</li>
                    }
                    @if (User.Identity.IsAuthenticated && !Roles.IsUserInRole("admin") && !Roles.IsUserInRole("guest"))
                    {
                        <li>@Html.ActionLink("Кабинет", "Index", "Cabinet")</li>
                    }
                    <li>@Html.ActionLink("О нас", "About", "Home")</li>
                    <li>@Html.ActionLink("Как связаться", "Contact", "Home")</li>
                    <li>
                        <a class=" dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Демо <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Все демо", "Index", "Demo")</li>
                            <li><a href="~/Content/sb-admin-2-1.0.5/index.html" target="_blank">Шаблон панели управления</a></li>
                            <li>@Html.ActionLink("Просто вывод таблицы с сортировкой и фильтрами", "SimpleTable", "Demo")</li>
                            <li>@Html.ActionLink("Фильтрация данных", "FilterTable", "Demo")</li>
                            <li>@Html.ActionLink("Inline редактирование", "InlineEditTable", "Demo")</li>
                            <li>@Html.ActionLink("Редактирование через модальную форму", "FullEditTable", "Demo")</li>
                            <li>@Html.ActionLink("Галочки для групповых операций", "GroupOperationTable", "Demo")</li>
                            <li>@Html.ActionLink("Двойная сортировка", "DoubleSortTable", "Demo")</li>
                            <li>@Html.ActionLink("Управляющие кнопки и показ вложенных элементов", "RowButtonsTable", "Demo")</li>
                            <li>@Html.ActionLink("Показ вложенной статистики по дням", "ShowStatTable", "Demo")</li>
                            <li>@Html.ActionLink("Настройка столбцов", "ColSettingsTable", "Demo")</li>
                            <li>@Html.ActionLink("Комментарии к элементам таблицы", "CommentsTable", "Demo")</li>
                            <li>@Html.ActionLink("Копирование другой строки", "CopyRowTable", "Demo")</li>
                            <li>@Html.ActionLink("Экспорт в Excel и PDF", "ExportExcelTable", "Demo")</li>
                            <li>@Html.ActionLink("Инструмент замены в определенных полях", "ReplaceToolTable", "Demo")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("AS Form - создание форм различной сложности", "ASForm", "Demo")</li>
                            <li>@Html.ActionLink("Cоздание простой формы", "SimpleForm", "Demo")</li>
                            <li class="divider"></li>                            
                            <li>@Html.ActionLink("Файловый менеджер", "Example", "FileEditor")</li>
                            <li>@Html.ActionLink("Новости", "GetArticleItems", "Article")</li>
                            <li>@Html.ActionLink("Компонент контроля действий", "AsCtrl", "Demo")</li>
                            <li>@Html.ActionLink("Графики", "Graphic", "Graphic")</li>
                            <li>@Html.ActionLink("AS Info - отображение уточняющего контента для элемента", "PopupInfo", "Demo")</li>
                            <li>@Html.ActionLink("Пример использования Signal R", "SignalR", "Demo")</li>
                            <li>@Html.ActionLink("Пример компонента одиночной замены картинки", "AsImageAsText", "Demo")</li>
                            <li>@Html.ActionLink("Пример элемента профиля пользователя", "ProfileFormUser", "Demo")</li>
                            <li>@Html.ActionLink("Обратный счетчик", "CountDown", "Demo")</li>
                            <li>@Html.ActionLink("Видео на фоне", "VideoBackground", "Demo")</li>
                            <li>@Html.ActionLink("Стандартные ответы на телефонные звонки", "PlayAudio", "Demo")</li>
                            <li>@Html.ActionLink("Горячие кнопки", "HotKeysDemo", "Demo")</li>
                           
                        </ul>
                    </li>
                    
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="body-content2">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Система разработки CRM (личных кабинетов) на заказ Ark AS (Web-automation.ru)</p>
                @Html.Partial("_ViewSwitcher")
            </footer>
        </div>
    </div>
    <div class="modal fade" id="asModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <p>One fine body&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary">ОК</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script src="~/js/AS/as.resources.js" charset="windows-1251"></script>

    @Scripts.Render("~/bundles/libs")
    @Scripts.Render("~/bundles/as")
    @Scripts.Render("~/bundles/highcharts")
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js?modules=core,widget,mouse,sortable"></script>

       <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function () { try { w.yaCounter32000186 = new Ya.Metrika({ id: 32000186, clickmap: true, trackLinks: true, accurateTrackBounce: true, webvisor: true }); } catch (e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/32000186" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
        @StackExchange.Profiling.MiniProfiler.RenderIncludes()
    @Html.GlimpseClient()
    @RenderSection("js", false)
    <script src="~/signalr/hubs"></script>
</body>
</html>

arkAS/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {    
      @Html.ActionLink("Полная Версия сайта", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @Html.ActionLink("Мобильная версия сайта", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}

arkAS/Views/Shared/js.cshtml
@Model